#!/usr/bin/env python3
"""Embed a microWakeWord streaming tflite model (+ its manifest) as a C header for the firmware.

  python tools/wakeword/embed_model.py model.tflite model.json firmware/src/mww_model.h
"""
import json
import sys
from pathlib import Path

tflite, manifest, out = Path(sys.argv[1]), Path(sys.argv[2]), Path(sys.argv[3])
data = tflite.read_bytes()
m = json.loads(manifest.read_text())
micro = m.get("micro", {})
cutoff = int(round(float(micro.get("probability_cutoff", 0.97)) * 255))
window = int(micro.get("sliding_window_size", 5))
arena = int(micro.get("tensor_arena_size", 30000))
step = int(micro.get("feature_step_size", 10))
lines = [
    "// Generated by tools/wakeword/embed_model.py — do not edit.",
    f"// {m.get('wake_word', '?')} (v{m.get('version', '?')}) from {tflite.name}, {len(data)} bytes",
    "#pragma once",
    "#include <stdint.h>",
    f'#define MWW_WAKE_WORD "{m.get("wake_word", "wake word")}"',
    f"#define MWW_PROBABILITY_CUTOFF {cutoff}",
    f"#define MWW_SLIDING_WINDOW {window}",
    f"#define MWW_TENSOR_ARENA {arena}",
    f"#define MWW_FEATURE_STEP_MS {step}",
    f"#define MWW_MODEL_SIZE {len(data)}",
    "alignas(16) static const unsigned char MWW_MODEL[] = {",
]
for i in range(0, len(data), 24):
    lines.append("  " + ",".join(f"0x{b:02x}" for b in data[i:i + 24]) + ",")
lines.append("};")
out.write_text("\n".join(lines) + "\n")
print(f"wrote {out} ({len(data)} bytes, cutoff {cutoff}/255, window {window}, arena {arena})")
